version: 0.0
os: linux

files:
  - source: target/aws-code-pipeline.jar
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: script/server_stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: script/server_start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: script/server_validate.sh
      timeout: 60
      runas: ec2-user